# Generated by Django 5.0 on 2023-12-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('collection', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('a_line', 'A-line'), ('ball_gown', 'Ball gown'), ('fit_and_flare', 'Fit-and-flare'), ('mermaid_trumpet', 'Mermaid or trumpet'), ('sheath', 'Sheath'), ('short', 'Short')], max_length=15)),
            ],
        ),
    ]
