# Generated by Django 5.0 on 2023-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_store_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='website_url',
            field=models.URLField(verbose_name='Website URL'),
        ),
    ]
