# Generated by Django 5.0 on 2023-12-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_store_city_alter_store_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='stores',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
