# Generated by Django 5.0 on 2023-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_dress_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='collection',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
