# Generated by Django 5.0 on 2023-12-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_dress_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dress',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='dress',
            name='collection',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dress',
            name='designer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dress',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dress')),
            ],
        ),
    ]
